#!/bin/bash -e

#Source debconf lib
. /usr/share/debconf/confmodule
    
### FUNCTIONS ###
do_title () {
    db_settitle raspisms/title
}


do_database_conf () {
    db_beginblock
        db_reset raspisms/database_auto_conf
        db_input high raspisms/database_auto_conf
    db_endblock
    db_go

    db_get raspisms/database_auto_conf
    if [ "$RET" = "false" ]; then
        return 0
    fi

    db_beginblock
        db_reset raspisms/database_admin_user
        db_input critical raspisms/database_admin_user
        
        db_reset raspisms/database_admin_password
        db_input critical raspisms/database_admin_password

        db_reset raspisms/database_host
        db_input medium raspisms/database_host
        
        db_reset raspisms/database_user
        db_input medium raspisms/database_user
        
        db_reset raspisms/database_password
        db_input medium raspisms/database_password
        
        db_reset raspisms/database_name
        db_input medium raspisms/database_name
    db_endblock
    db_go
}

do_app_user () {
    db_beginblock
        db_reset raspisms/app_user_email
        db_input medium raspisms/app_user_email

        db_reset raspisms/app_user_password
        db_input medium raspisms/app_user_password
    db_endblock
    db_go
}

do_app_mail () {
    db_beginblock
        db_reset raspisms/app_mail_config
        db_input high raspisms/app_mail_config
    db_endblock
    db_go

    db_get raspisms/app_mail_config
    if [ "$RET" = "false" ]; then
        return 0
    fi

    db_beginblock
        db_reset raspisms/app_mail_smtp_user
        db_input medium raspisms/app_mail_smtp_user

        db_reset raspisms/app_mail_smtp_password
        db_input medium raspisms/app_mail_smtp_password
        
        db_reset raspisms/app_mail_smtp_host
        db_input medium raspisms/app_mail_smtp_host

        db_reset raspisms/app_mail_smtp_tls
        db_input medium raspisms/app_mail_smtp_tls

        db_reset raspisms/app_mail_smtp_port
        db_input medium raspisms/app_mail_smtp_port

        db_reset raspisms/app_mail_from
        db_input medium raspisms/app_mail_from
    db_endblock
    db_go
}

do_apache_conf () {
    db_beginblock
        db_reset raspisms/apache_auto_conf
        db_input medium raspisms/apache_auto_conf
    db_endblock
    db_go
}

do_systemd_conf () {
    db_beginblock
        db_reset raspisms/systemd_auto_conf
        db_input medium raspisms/systemd_auto_conf
    db_endblock
    db_go
}


#Main
do_title
do_database_conf
do_app_user
do_app_mail
do_apache_conf
do_systemd_conf
