#!/bin/bash

#Source debconf lib
. /usr/share/debconf/confmodule

SCRIPT_DIR=$(dirname $(readlink -f $0))

### CONF VARS ###

INSTALL_DIR="/usr/share/raspisms"


### Functions ###
error_report () {
    printf "\n\nError on line $(caller)\n\n";
    exit 1
}


do_delete_user () {
    if [ ! "$1" == "remove" ]; then
        return 0
    fi

    printf "\n"
    printf "Delete user raspisms.\n"
    
    cd $INSTALL_DIR

    deluser raspisms
    delgroup raspisms

    printf "\n"
    printf "Done.\n"
    printf "\n"
}


do_debconf_purge () {
    if [ ! "$1" == "purge" ]; then
        return 0
    fi
    
    if [ -e /usr/share/debconf/confmodule ]; then
        printf "\n"
        printf "Purge debconf.\n"
        db_reset raspisms
        db_purge
    fi

    printf "\n"
    printf "Done.\n"
    printf "\n"
}


do_delete_user || exit 1
do_debconf_purge || exit 1

# Automatically added by dh_installdebconf/11.1.6ubuntu2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

